# Configuraci√≥n de Supabase para el proyecto

[api]
enabled = true
port = 54321
schemas = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[functions.send-expiration-emails]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.activate-subscription]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.webhook-paypal]
verify_jwt = false

[functions.cron-check-subscriptions]
verify_jwt = false

[functions.mp-create-subscription]
verify_jwt = true

[functions.mp-manage-subscription]
verify_jwt = false

[functions.webhook-mercadopago]
verify_jwt = false
